services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgis:/var/lib/postgis/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=locations
